on:
  push:
    branches:
      - 'main'
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Install pandoc 
        run: |
          sudo apt-get update
          sudo apt-get install pandoc bash
      - run: sh ./deploy.sh
